/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module counter(clk, enable, rst, count_0, count_1, count_2, count_3);
  wire CONST0;
  wire CONST1;
  input clk;
  output count_0;
  output count_1;
  output count_2;
  output count_3;
  input enable;
  input rst;
  wire tmp_ADD_0_0;
  wire tmp_ADD_0_1;
  wire tmp_ADD_0_2;
  wire tmp_ADD_0_3;
  wire tmp_and_1;
  wire tmp_and_13;
  wire tmp_and_14;
  wire tmp_and_15;
  wire tmp_and_2;
  wire tmp_and_3;
  wire tmp_and_7;
  wire tmp_and_8;
  wire tmp_and_9;
  wire tmp_mux_24;
  wire tmp_mux_25;
  wire tmp_mux_26;
  wire tmp_mux_27;
  wire tmp_mux_28;
  wire tmp_mux_29;
  wire tmp_mux_30;
  wire tmp_mux_31;
  wire tmp_or_10;
  wire tmp_or_11;
  wire tmp_or_16;
  wire tmp_or_17;
  wire tmp_or_4;
  wire tmp_or_5;
  wire tmp_xor_0;
  wire tmp_xor_12;
  wire tmp_xor_18;
  wire tmp_xor_6;
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) count_0_reg /* _00_ */ (
    .CLK(clk),
    .D(tmp_mux_25),
    .Q(count_0)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) count_1_reg /* _01_ */ (
    .CLK(clk),
    .D(tmp_mux_27),
    .Q(count_1)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) count_2_reg /* _02_ */ (
    .CLK(clk),
    .D(tmp_mux_29),
    .Q(count_2)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) count_3_reg /* _03_ */ (
    .CLK(clk),
    .D(tmp_mux_31),
    .Q(count_3)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _04_ (
    .A({ 1'h1, count_0 }),
    .Y(tmp_xor_0)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _05_ (
    .A({ 1'h0, count_1 }),
    .Y(tmp_and_7)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _06_ (
    .A({ tmp_or_5, count_1 }),
    .Y(tmp_and_8)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _07_ (
    .A({ tmp_or_5, 1'h0 }),
    .Y(tmp_and_9)
  );
  \$lut  #(
    .LUT(4'he),
    .WIDTH(32'd2)
  ) _08_ (
    .A({ tmp_and_8, tmp_and_7 }),
    .Y(tmp_or_10)
  );
  \$lut  #(
    .LUT(4'he),
    .WIDTH(32'd2)
  ) _09_ (
    .A({ tmp_and_9, tmp_or_10 }),
    .Y(tmp_or_11)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _10_ (
    .A({ 1'h0, count_2 }),
    .Y(tmp_xor_12)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _11_ (
    .A({ tmp_or_11, tmp_xor_12 }),
    .Y(tmp_ADD_0_2)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _12_ (
    .A({ 1'h0, count_2 }),
    .Y(tmp_and_13)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _13_ (
    .A({ tmp_or_11, count_2 }),
    .Y(tmp_and_14)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _14_ (
    .A({ tmp_or_11, 1'h0 }),
    .Y(tmp_and_15)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _15_ (
    .A({ 1'h0, tmp_xor_0 }),
    .Y(tmp_ADD_0_0)
  );
  \$lut  #(
    .LUT(4'he),
    .WIDTH(32'd2)
  ) _16_ (
    .A({ tmp_and_14, tmp_and_13 }),
    .Y(tmp_or_16)
  );
  \$lut  #(
    .LUT(4'he),
    .WIDTH(32'd2)
  ) _17_ (
    .A({ tmp_and_15, tmp_or_16 }),
    .Y(tmp_or_17)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _18_ (
    .A({ 1'h0, count_3 }),
    .Y(tmp_xor_18)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _19_ (
    .A({ tmp_or_17, tmp_xor_18 }),
    .Y(tmp_ADD_0_3)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _20_ (
    .A({ count_0, tmp_ADD_0_0, enable }),
    .Y(tmp_mux_24)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _21_ (
    .A({ 1'h1, count_0 }),
    .Y(tmp_and_1)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _22_ (
    .A({ tmp_mux_24, 1'h0, rst }),
    .Y(tmp_mux_25)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _23_ (
    .A({ count_1, tmp_ADD_0_1, enable }),
    .Y(tmp_mux_26)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _24_ (
    .A({ tmp_mux_26, 1'h0, rst }),
    .Y(tmp_mux_27)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _25_ (
    .A({ count_2, tmp_ADD_0_2, enable }),
    .Y(tmp_mux_28)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _26_ (
    .A({ tmp_mux_28, 1'h0, rst }),
    .Y(tmp_mux_29)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _27_ (
    .A({ count_3, tmp_ADD_0_3, enable }),
    .Y(tmp_mux_30)
  );
  \$lut  #(
    .LUT(8'hd8),
    .WIDTH(32'd3)
  ) _28_ (
    .A({ tmp_mux_30, 1'h0, rst }),
    .Y(tmp_mux_31)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _29_ (
    .A({ 1'h0, count_0 }),
    .Y(tmp_and_2)
  );
  \$lut  #(
    .LUT(4'h8),
    .WIDTH(32'd2)
  ) _30_ (
    .A(2'h1),
    .Y(tmp_and_3)
  );
  \$lut  #(
    .LUT(4'he),
    .WIDTH(32'd2)
  ) _31_ (
    .A({ tmp_and_2, tmp_and_1 }),
    .Y(tmp_or_4)
  );
  \$lut  #(
    .LUT(4'he),
    .WIDTH(32'd2)
  ) _32_ (
    .A({ tmp_and_3, tmp_or_4 }),
    .Y(tmp_or_5)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _33_ (
    .A({ 1'h0, count_1 }),
    .Y(tmp_xor_6)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _34_ (
    .A({ tmp_or_5, tmp_xor_6 }),
    .Y(tmp_ADD_0_1)
  );
  assign CONST0 = 1'h0;
  assign CONST1 = 1'h1;
endmodule
