/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module counter(clk, rst, enable, \count[0] , \count[1] , \count[2] , \count[3] );
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input clk;
  output \count[0] ;
  output \count[1] ;
  output \count[2] ;
  output \count[3] ;
  input enable;
  input rst;
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \count_reg[0]  /* _17_ */ (
    .CLK(clk),
    .D(_00_),
    .Q(\count[0] )
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \count_reg[1]  /* _18_ */ (
    .CLK(clk),
    .D(_01_),
    .Q(\count[1] )
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \count_reg[2]  /* _19_ */ (
    .CLK(clk),
    .D(_02_),
    .Q(\count[2] )
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) \count_reg[3]  /* _20_ */ (
    .CLK(clk),
    .D(_03_),
    .Q(\count[3] )
  );
  \$lut  #(
    .LUT(2'h1),
    .WIDTH(32'd1)
  ) _21_ (
    .A(rst),
    .Y(_04_)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _22_ (
    .A({ \count[2] , _10_ }),
    .Y(_11_)
  );
  \$lut  #(
    .LUT(8'hca),
    .WIDTH(32'd3)
  ) _23_ (
    .A({ enable, _11_, _09_ }),
    .Y(_12_)
  );
  \$lut  #(
    .LUT(4'h2),
    .WIDTH(32'd2)
  ) _24_ (
    .A({ _12_, _04_ }),
    .Y(_02_)
  );
  \$lut  #(
    .LUT(2'h1),
    .WIDTH(32'd1)
  ) _25_ (
    .A(\count[3] ),
    .Y(_13_)
  );
  \$lut  #(
    .LUT(4'h2),
    .WIDTH(32'd2)
  ) _26_ (
    .A({ _10_, \count[2]  }),
    .Y(_14_)
  );
  \$lut  #(
    .LUT(4'h6),
    .WIDTH(32'd2)
  ) _27_ (
    .A({ _13_, _14_ }),
    .Y(_15_)
  );
  \$lut  #(
    .LUT(8'hca),
    .WIDTH(32'd3)
  ) _28_ (
    .A({ enable, _15_, _13_ }),
    .Y(_16_)
  );
  \$lut  #(
    .LUT(4'h2),
    .WIDTH(32'd2)
  ) _29_ (
    .A({ _16_, _04_ }),
    .Y(_03_)
  );
  \$lut  #(
    .LUT(4'h9),
    .WIDTH(32'd2)
  ) _30_ (
    .A({ \count[0] , enable }),
    .Y(_05_)
  );
  \$lut  #(
    .LUT(4'h2),
    .WIDTH(32'd2)
  ) _31_ (
    .A({ _05_, _04_ }),
    .Y(_00_)
  );
  \$lut  #(
    .LUT(2'h1),
    .WIDTH(32'd1)
  ) _32_ (
    .A(\count[1] ),
    .Y(_06_)
  );
  \$lut  #(
    .LUT(4'h9),
    .WIDTH(32'd2)
  ) _33_ (
    .A({ \count[0] , \count[1]  }),
    .Y(_07_)
  );
  \$lut  #(
    .LUT(8'hca),
    .WIDTH(32'd3)
  ) _34_ (
    .A({ enable, _07_, _06_ }),
    .Y(_08_)
  );
  \$lut  #(
    .LUT(4'h2),
    .WIDTH(32'd2)
  ) _35_ (
    .A({ _08_, _04_ }),
    .Y(_01_)
  );
  \$lut  #(
    .LUT(2'h1),
    .WIDTH(32'd1)
  ) _36_ (
    .A(\count[2] ),
    .Y(_09_)
  );
  \$lut  #(
    .LUT(4'h7),
    .WIDTH(32'd2)
  ) _37_ (
    .A({ \count[0] , \count[1]  }),
    .Y(_10_)
  );
endmodule
